declare module 'vue' {
  export interface GlobalComponents {
    SAccordion: typeof import('./components/accordion/accordion.vue').default
    SAccordionItem: typeof import('./components/accordion/accordion-item.vue').default
    SActionSheet: typeof import('./components/action-sheet/action-sheet.vue').default
    SActionSheetItem: typeof import('./components/action-sheet/action-sheet-item.vue').default
    SAlert: typeof import('./components/alert/alert.vue').default
    SAvatar: typeof import('./components/avatar/avatar.vue').default
    SAvatarGroup: typeof import('./components/avatar/avatar-group.vue').default
    SBackTop: typeof import('./components/back-top/back-top.vue').default
    SBadge: typeof import('./components/badge/badge.vue').default
    SBarcode: typeof import('./components/barcode/barcode.vue').default
    SButton: typeof import('./components/button/button.vue').default
    SCalendar: typeof import('./components/calendar/calendar.vue').default
    SCalendarInput: typeof import('./components/calendar-input/calendar-input.vue').default
    SCalendarPopout: typeof import('./components/calendar-popout/calendar-popout.vue').default
    SCard: typeof import('./components/card/card.vue').default
    SCascader: typeof import('./components/cascader/cascader.vue').default
    SCascaderInput: typeof import('./components/cascader-input/cascader-input.vue').default
    SCascaderPopout: typeof import('./components/cascader-popout/cascader-popout.vue').default
    SCheckbox: typeof import('./components/checkbox/checkbox.vue').default
    SCheckboxGroup: typeof import('./components/checkbox/checkbox-group.vue').default
    SCheckboxInput: typeof import('./components/checkbox-input/checkbox-input.vue').default
    SCheckboxPopout: typeof import('./components/checkbox-popout/checkbox-popout.vue').default
    SCol: typeof import('./components/layout/col.vue').default
    SCollapse: typeof import('./components/collapse/collapse.vue').default
    SColorPicker: typeof import('./components/color-picker/color-picker.vue').default
    SColorPickerInput: typeof import('./components/color-picker-input/color-picker-input.vue').default
    SColorPickerPopout: typeof import('./components/color-picker-popout/color-picker-popout.vue').default
    SCompact: typeof import('./components/compact/compact.vue').default
    SCoolIcon: typeof import('./components/cool-icon/cool-icon.vue').default
    SCountDown: typeof import('./components/count-down/count-down.vue').default
    SCountTo: typeof import('./components/count-to/count-to.vue').default
    SCropImage: typeof import('./components/crop-image/crop-image.vue').default
    SDateStrip: typeof import('./components/date-strip/date-strip.vue').default
    SDatetimePicker: typeof import('./components/datetime-picker/datetime-picker.vue').default
    SDatetimePickerInput: typeof import('./components/datetime-picker-input/datetime-picker-input.vue').default
    SDatetimePickerPopout: typeof import('./components/datetime-picker-popout/datetime-picker-popout.vue').default
    SDatetimeRangePicker: typeof import('./components/datetime-range-picker/datetime-range-picker.vue').default
    SDatetimeRangePickerInput: typeof import('./components/datetime-range-picker-input/datetime-range-picker-input.vue').default
    SDatetimeRangePickerPopout: typeof import('./components/datetime-range-picker-popout/datetime-range-picker-popout.vue').default
    SDescriptions: typeof import('./components/descriptions/descriptions.vue').default
    SDescriptionsItem: typeof import('./components/descriptions/descriptions-item.vue').default
    SDialog: typeof import('./components/dialog/dialog.vue').default
    SDivider: typeof import('./components/divider/divider.vue').default
    SDnd: typeof import('./components/dnd/dnd.vue').default
    SDndHandle: typeof import('./components/dnd/dnd-handle.vue').default
    SDndItem: typeof import('./components/dnd/dnd-item.vue').default
    SDropdown: typeof import('./components/dropdown/dropdown.vue').default
    SDropdownItem: typeof import('./components/dropdown/dropdown-item.vue').default
    SEllipsis: typeof import('./components/ellipsis/ellipsis.vue').default
    SEmpty: typeof import('./components/empty/empty.vue').default
    SFab: typeof import('./components/fab/fab.vue').default
    SFabItem: typeof import('./components/fab/fab-item.vue').default
    SFloatingBubble: typeof import('./components/floating-bubble/floating-bubble.vue').default
    SFloatingPanel: typeof import('./components/floating-panel/floating-panel.vue').default
    SForm: typeof import('./components/form/form.vue').default
    SFormItem: typeof import('./components/form/form-item.vue').default
    SFormItemPlain: typeof import('./components/form-plain/form-item-plain.vue').default
    SFormPlain: typeof import('./components/form-plain/form-plain.vue').default
    SGrid: typeof import('./components/grid/grid.vue').default
    SGridItem: typeof import('./components/grid/grid-item.vue').default
    SIcon: typeof import('./components/icon/icon.vue').default
    SImage: typeof import('./components/image/image.vue').default
    SIndexes: typeof import('./components/indexes/indexes.vue').default
    SIndexesAnchor: typeof import('./components/indexes/indexes-anchor.vue').default
    SInput: typeof import('./components/input/input.vue').default
    SKeyboard: typeof import('./components/keyboard/keyboard.vue').default
    SKeyboardPopout: typeof import('./components/keyboard-popout/keyboard-popout.vue').default
    SList: typeof import('./components/list/list.vue').default
    SListItem: typeof import('./components/list/list-item.vue').default
    SLoadMore: typeof import('./components/load-more/load-more.vue').default
    SLoading: typeof import('./components/loading/loading.vue').default
    SMarquee: typeof import('./components/marquee/marquee.vue').default
    SMenu: typeof import('./components/menu/menu.vue').default
    SMenuItem: typeof import('./components/menu-item/menu-item.vue').default
    SMotion: typeof import('./components/motion/motion.vue').default
    SNavbar: typeof import('./components/navbar/navbar.vue').default
    SNavbarItem: typeof import('./components/navbar/navbar-item.vue').default
    SNavbarPit: typeof import('./components/navbar-pit/navbar-pit.vue').default
    SNoticeBar: typeof import('./components/notice-bar/notice-bar.vue').default
    SNotify: typeof import('./components/notify/notify.vue').default
    SOverlay: typeof import('./components/overlay/overlay.vue').default
    SPagination: typeof import('./components/pagination/pagination.vue').default
    SPasswordInput: typeof import('./components/password-input/password-input.vue').default
    SPicker: typeof import('./components/picker/picker.vue').default
    SPickerInput: typeof import('./components/picker-input/picker-input.vue').default
    SPickerPopout: typeof import('./components/picker-popout/picker-popout.vue').default
    SPickerView: typeof import('./components/picker-view/picker-view.tsx').default
    SPickerViewColumn: typeof import('./components/picker-view/picker-view-column.tsx').default
    SPopout: typeof import('./components/popout/popout.vue').default
    SPopoutInput: typeof import('./components/popout-input/popout-input.vue').default
    SPopover: typeof import('./components/popover/popover.vue').default
    SPopup: typeof import('./components/popup/popup.vue').default
    SPreviewImage: typeof import('./components/preview-image/preview-image.vue').default
    SProgressBar: typeof import('./components/progress-bar/progress-bar.vue').default
    SProgressCircle: typeof import('./components/progress-circle/progress-circle.vue').default
    SPullDownRefresh: typeof import('./components/pull-down-refresh/pull-down-refresh.vue').default
    SPuzzleVerify: typeof import('./components/puzzle-verify/puzzle-verify.vue').default
    SQrcode: typeof import('./components/qrcode/qrcode.vue').default
    SRadio: typeof import('./components/radio/radio.vue').default
    SRadioGroup: typeof import('./components/radio/radio-group.vue').default
    SRadioInput: typeof import('./components/radio-input/radio-input.vue').default
    SRadioPopout: typeof import('./components/radio-popout/radio-popout.vue').default
    SRate: typeof import('./components/rate/rate.vue').default
    SReadMore: typeof import('./components/read-more/read-more.vue').default
    SResult: typeof import('./components/result/result.vue').default
    SRotateVerify: typeof import('./components/rotate-verify/rotate-verify.vue').default
    SRow: typeof import('./components/layout/row.vue').default
    SScrollList: typeof import('./components/scroll-list/scroll-list.vue').default
    SScrollSpy: typeof import('./components/scroll-spy/scroll-spy.vue').default
    SScrollSpyAnchor: typeof import('./components/scroll-spy/scroll-spy-anchor.vue').default
    SSearch: typeof import('./components/search/search.vue').default
    SSegmented: typeof import('./components/segmented/segmented.vue').default
    SSegmentedItem: typeof import('./components/segmented/segmented-item.vue').default
    SSelect: typeof import('./components/select/select.vue').default
    SSelectInput: typeof import('./components/select-input/select-input.vue').default
    SSelectOption: typeof import('./components/select/select-option.vue').default
    SSelectOptionGroup: typeof import('./components/select/select-option-group.vue').default
    SSelectPopout: typeof import('./components/select-popout/select-popout.vue').default
    SShareSheet: typeof import('./components/share-sheet/share-sheet.vue').default
    SShareSheetIcon: typeof import('./components/share-sheet-icon/share-sheet-icon.vue').default
    SShareSheetItem: typeof import('./components/share-sheet/share-sheet-item.vue').default
    SShareSheetRow: typeof import('./components/share-sheet/share-sheet-row.vue').default
    SSidebar: typeof import('./components/sidebar/sidebar.vue').default
    SSidebarItem: typeof import('./components/sidebar/sidebar-item.vue').default
    SSignature: typeof import('./components/signature/signature.vue').default
    SSkeleton: typeof import('./components/skeleton/skeleton.vue').default
    SSkeletonAvatar: typeof import('./components/skeleton/skeleton-avatar.vue').default
    SSkeletonBlock: typeof import('./components/skeleton-block/skeleton-block.vue').default
    SSkeletonParagraph: typeof import('./components/skeleton/skeleton-paragraph.vue').default
    SSkeletonTitle: typeof import('./components/skeleton/skeleton-title.vue').default
    SSlideVerify: typeof import('./components/slide-verify/slide-verify.vue').default
    SSlider: typeof import('./components/slider/slider.vue').default
    SSpace: typeof import('./components/space/space.vue').default
    SStatusBar: typeof import('./components/status-bar/status-bar.vue').default
    SStep: typeof import('./components/steps/step.vue').default
    SStepper: typeof import('./components/stepper/stepper.vue').default
    SSteps: typeof import('./components/steps/steps.vue').default
    SSticky: typeof import('./components/sticky/sticky.vue').default
    SStickyBox: typeof import('./components/sticky/sticky-box.vue').default
    SSwipeAction: typeof import('./components/swipe-action/swipe-action.vue').default
    SSwiper: typeof import('./components/swiper/swiper.tsx').default
    SSwiperItem: typeof import('./components/swiper/swiper-item.tsx').default
    SSwitch: typeof import('./components/switch/switch.vue').default
    STab: typeof import('./components/tab/tab.vue').default
    STabbar: typeof import('./components/tabbar/tabbar.vue').default
    STabbarItem: typeof import('./components/tabbar/tabbar-item.vue').default
    STabbarPit: typeof import('./components/tabbar-pit/tabbar-pit.vue').default
    STable: typeof import('./components/table/table.vue').default
    STabs: typeof import('./components/tabs/tabs.vue').default
    STag: typeof import('./components/tag/tag.vue').default
    SText: typeof import('./components/text/text.vue').default
    STimeline: typeof import('./components/timeline/timeline.vue').default
    STimelineItem: typeof import('./components/timeline/timeline-item.vue').default
    SToast: typeof import('./components/toast/toast.vue').default
    STree: typeof import('./components/tree/tree.vue').default
    SUpload: typeof import('./components/upload/upload.vue').default
    SWaterfall: typeof import('./components/waterfall/waterfall.vue').default
    SWaterfallItem: typeof import('./components/waterfall/waterfall-item.vue').default
    SWaterfallLoad: typeof import('./components/waterfall/waterfall-load.vue').default
    SWatermark: typeof import('./components/watermark/watermark.vue').default
  }
}

export {}
